name: Build signed APK
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Decode the keystore from base64 in secrets and store in /android-app
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo $ENCODED_STRING | base64 -d > keystore.jks

      - name: Build Release apk and bundle
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease --stacktrace

      - name: File paths to variables
        id: releaseFiles
        run: |
          echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_OUTPUT
          echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
           name: release-artifacts
           path: |
             ${{ steps.releaseFiles.outputs.apkfile }}
             ${{ steps.releaseFiles.outputs.aabfile }}
