name: Build signed APK
on:
  workflow_dispatch:
    inputs:
      make-draft:
        description: "Make draft release? yes/no"
        required: true
        default: "yes"

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Decode the keystore from base64 in secrets and store in /android-app
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: echo $ENCODED_STRING | base64 -d > keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release apk
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: ./gradlew assembleRelease --stacktrace

      - name: File paths to variables
        id: releaseFiles
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
           name: apk-file
           path: ${{ steps.releaseFiles.outputs.apkfile }}
           if-no-files-found: error

  draft-release:
    needs: build-apk
    runs-on: ubuntu-latest
    if: ${{ inputs.make-draft == 'yes' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded
          pattern: "*-file"
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: downloaded/**
          name: Draft release
          draft: true
